services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch --force_polling --verbose --livereload
    platform: linux/amd64
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll